# Generated by Django 3.2.7 on 2022-01-11 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm_interface', '0002_tb2_url_details_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tb2_url_details_table',
            old_name='article_data_id',
            new_name='article_url',
        ),
    ]
