# Generated by Django 3.2.7 on 2022-05-06 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_interface', '0003_rename_article_data_id_tb2_url_details_table_article_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_url', models.CharField(max_length=767, unique=True)),
            ],
            options={
                'db_table': 'article',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleImgConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=20)),
                ('scrape_type', models.CharField(max_length=20)),
                ('attribute_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'article_img_configuration',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArticlePublishDateConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=20)),
                ('scrape_type', models.CharField(max_length=20)),
                ('attribute_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'article_publish_date_configuration',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleTextConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=20)),
                ('scrape_type', models.CharField(max_length=20)),
                ('attribute_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'article_text_configuration',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleTopicHeadlineConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_tag_name', models.CharField(max_length=20)),
                ('child_tag_name', models.CharField(max_length=20)),
                ('scrape_type', models.CharField(max_length=20)),
                ('attribute_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'article_topic_headline_configuration',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleUrlConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=20)),
                ('scrape_type', models.CharField(max_length=20)),
                ('attribute_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'article_url_configuration',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DomainUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=600)),
            ],
            options={
                'db_table': 'domain_url',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnprocesssedScrapeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unprocessed_news_topic', models.TextField()),
                ('unprocessed_news_description', models.TextField()),
                ('publication_date', models.CharField(max_length=767)),
                ('image_href', models.CharField(max_length=767)),
                ('scrape_time_stamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'unprocesssed_scrape_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.IntegerField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
